FROM alpine:3.11 as builder

WORKDIR /root/
ENV EDGE_ARCH arm64
ARG downloadscript_path=download_kubeedge.sh
ENV downloadscript_path ${downloadscript_path}

COPY ${downloadscript_path} /
RUN umask 022
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories

RUN apk update
RUN apk --no-cache add ca-certificates libdrm curl
RUN mkdir -p /etc/kubeedge
RUN chmod +x /download_kubeedge.sh;
RUN /download_kubeedge.sh ${EDGE_ARCH}

FROM ubuntu:18.04 as server
COPY --from=0 /usr/local/bin/cloudcore /usr/local/bin

CMD ["edgecore --config /etc/kubeedge/config/edgecore.yaml > /var/log/kubeedge/edgecore.log 2>&1"]