FROM alpine:3.11 as server

WORKDIR /root/
ENV EDGE_ARCH arm64
COPY download_kubeedge.sh /
RUN umask 022
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories

RUN apk update
RUN apk --no-cache add ca-certificates libdrm curl
RUN mkdir -p /etc/kubeedge
RUN chmod +x /download_kubeedge.sh;
RUN /download_kubeedge.sh ${EDGE_ARCH}

CMD ["nohup edgecore --config /etc/kubeedge/config/edgecore.yaml > /var/log/kubeedge/edgecore.log 2>&1 &"]