FROM golang:1.13.7-alpine3.11 as builder

ENV GO111MODULE on
ENV GOPROXY https://goproxy.cn,direct
RUN umask 022
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories

RUN mkdir -p /etc/apulisedge
RUN apk update
RUN apk --no-cache add curl git build-base

RUN mkdir -p /go/src
RUN mkdir -p /go/bin
RUN cd /go/src; git clone https://oauth2:FaEZpionqFc619w_3UvB@apulis-gitlab.apulis.cn/apulis/apulisedge.git apulisedge
RUN cd /go/src/apulisedge; git checkout feature/cloud_dev
RUN cd /go/src/apulisedge/cloud/cmd; GO111MODULE=${GO111MODULE} go build -v -o /go/bin/ApulisEdgeCloud

FROM alpine:3.11 as server
RUN apk --no-cache add ca-certificates libdrm
WORKDIR /root/
COPY --from=0 /go/bin/ApulisEdgeCloud .

CMD ["./ApulisEdgeCloud"]