FROM golang:1.13.7-alpine3.11 as builder

ENV GO111MODULE on
RUN umask 022
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories

RUN apk update
RUN apk --no-cache add git build-base

RUN mkdir -p /go/src/apulis
ADD agent /go/src/apulis/apulisedge-agent
RUN cd /go/src/apulis/apulisedge-agent; GO111MODULE=${GO111MODULE} go build -o /go/bin/ApulisEdgeAgent;


FROM alpine:3.11 as server
RUN apk --no-cache add ca-certificates libdrm
WORKDIR /root/
COPY --from=0 /go/bin/ApulisEdgeAgent .

CMD ["./ApulisEdgeAgent"]