FROM alpine:3.11 as builder

WORKDIR /root/
ENV CLOUD_ARCH amd64
ARG downloadscript_path=download_kubeedge.sh
ENV downloadscript_path ${downloadscript_path}

COPY ${downloadscript_path} /
RUN umask 022
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories

RUN mkdir -p /etc/kubeedge
RUN apk update
RUN apk --no-cache add curl ca-certificates libdrm
RUN chmod +x /download_kubeedge.sh;
RUN /download_kubeedge.sh ${CLOUD_ARCH}

FROM ubuntu:18.04 as server
COPY --from=0 /usr/local/bin/cloudcore /usr/local/bin

CMD ["cloudcore --config /etc/kubeedge/config/cloudcore.yaml > /var/log/kubeedge/cloudcore.log 2>&1"]