FROM alpine:3.11

WORKDIR /root/
ENV CLOUD_ARCH amd64
COPY download_kubeedge.sh /
RUN umask 022
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories

RUN mkdir -p /etc/kubeedge
RUN apk update
RUN apk --no-cache add curl ca-certificates libdrm
RUN chmod +x /download_kubeedge.sh;
RUN /download_kubeedge.sh ${CLOUD_ARCH}

CMD ["nohup cloudcore --config /etc/kubeedge/config/cloudcore.yaml > /var/log/kubeedge/cloudcore.log 2>&1 &"]