FROM golang:1.13.7-alpine3.11 as builder

ENV GO111MODULE on
RUN umask 022
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories

RUN mkdir -p /etc/apulisedge
RUN apk update
RUN apk --no-cache add curl git build-base

RUN mkdir -p /go/src/apulis
ADD ./cloud /go/src/apulis/apulisedge-cloud
RUN cd /go/src/apulis/apulisedge-cloud; GO111MODULE=${GO111MODULE} go build -o /go/bin/ApulisEdgeCloud;


FROM alpine:3.11 as server
RUN apk --no-cache add ca-certificates libdrm
WORKDIR /root/
COPY --from=0 /go/bin/ApulisEdgeCloud .

CMD ["./ApulisEdgeCloud"]