kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: apulisedge-mysql-data-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.apulis.mysql.dataClaimCapacity }}
