apiVersion: v1
kind: ConfigMap
metadata:
  name: apulisedge-cloud-cm
  namespace: {{ .Values.apulis.namespace }}
data:
  cloud.yaml: |+
    {{- with .Values.apulis.cloud.config }}
    Portal:
      NodeCheckerInterval: 5
      ApplicationCheckerInterval: 5
      Http:
        Enable: true
        Address: 0.0.0.0
        Port: {{ .portalPort }}

    CloudHub:
      Websocket:
        Enable: true
        Address: 0.0.0.0
        Port: {{ .hubPort }}

    Log:
      # 6: trace, 5: debug, 4: info
      Level: 4
      WriteFile: true
      FileDir: /var/log/apulisedge/
      FileName: apulis_edge_cloud.log

    Db:
      UserName: {{ .dbUser }}
      Password: {{ .dbPass }}
      Host: {{ .dbHost }}
      Port: 3306
      Database: ApulisEdgeCloudDB
      MaxOpenConns: 10
      MaxIdleConns: 2

    Authentication:
      AuthType: AiArts
      AiArtsAuth:
        key: "Sign key for JWT"

    DebugModel: false

    Clusters:
      {{- with $.Values.apulis.cloud.env }}
      - Id: 0
        Desc: "for test"
        Domain: {{ .cloudHostName }}}
        KubeMaster: "https://{{ .kubeMasterHostName }}:{{ .kubeMasterPort }}"
        KubeConfFile: "/root/.kube/config"
        HarborAddress: {{ .harborHostName }}}
        HarborProject: "apulisedge"
        HarborUser: "robot$cloud"
        HarborPasswd: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDgyNjQ4NjksImlzcyI6ImhhcmJvci10b2tlbi1kZWZhdWx0SXNzdWVyIiwiaWQiOjIsInBpZCI6MTksImFjY2VzcyI6W3siUmVzb3VyY2UiOiIvcHJvamVjdC8xOS9yZXBvc2l0b3J5IiwiQWN0aW9uIjoicHVzaCIsIkVmZmVjdCI6IiJ9XX0.HutFfituzZUV1ljsqK9rxauJ6dfrhb_s2vbaYD3M_YGMVFbPfrNPrvGitHrDSpWIxXhDpS4E7xRj4_DVFq6X_DEt-ZKQgs86jv6QNovM5BBgbKJloyDVlWM-ZBOGDOn19U4YVHHfpVdwW27FAJSaAi5BQjrCe79cft2OhOAqJYXv9Q4Gmdwq4oHyiGsAA4xraVdyA7N5uMe4Uw4C9MBmJuI0s9gsaJNoHpy6ndi_JGx1ESe_Gq1JTiX9h5MQVHy-zr14gUHjdxTMrRXeU455oOwHoiM2w2r255PdRUQEYip8W60lGe93crJhBvvBZEd6V6fTa7aM1fkYXuZv8INTyImg-BVGiGRWQI5IUi9jYtnTTbHX4bTcvR0lUEdi0_yAYUuDNz49mwQGCFzg0T-_hNik5rx3OJUzcuvIRrJoKtYCv-CX3cJmRnsjaYyOub5tQqUmC6azIxmkYaNWhenrt0SMlGZ6jxaaDe3ptTfOAgIpsBX4lydS_BLNdCqwKBXkBdQc68ZW4rAtrQegH6rpWQxQEIaYhUzpiVRqscn3FqP_vKt1zhCXTPRvgWszX34Eobey8hvLPIEEtYkgV8uczs7_iiWWxAJWpD60VM244a516h2Ig59Xr9Qt7_QXU9HQ97P8oEFTUV_imIQKwZCbjQJ4Zym_RruLuUaMRZZi3XM"
        DownloadAddress: "{{ .cloudHostName }}:{{ .downloadSvrPort }}"
      {{- end}}
    {{- end }}