apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apulis.mysql.dbAppName }}
  namespace: {{ .Values.apulis.namespace }}
spec:
  selector:
    app: {{ .Values.apulis.mysql.dbAppName }}
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP