{{- $setNfs := (eq .Values.apulis.mysql.persistentVolumeType "nfs") }}
{{- if $setNfs }}
{{- range .Values.apulis.mysql.persistentVolumes }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .name }}
spec:
  capacity:
    storage: {{ .capacity }}
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  mountOptions:
    - timeo=20
    - tcp
  nfs:
    {{- if not (empty $.Values.apulis.mysql.nfsServer) }}
    server: {{ $.Values.apulis.mysql.nfsServer }}
    {{- end }}
    {{- if not (empty .path) }}
    path: {{ .path }}
    {{- end }}
{{- end }}
{{- end }}






