namespace: default
mysql:
  dbAppName: apulis-mysql
  dbUser: root
  dbPass: root@123
  image:
    repository: docker.io/mysql/mysql-server
    tag: "8.0"

  exposePort:
    enable: true
    port: 30060

  dataClaimCapacity: 2000Mi
  logClaimCapacity: 1000Mi

  persistentVolumeType: nfs
  nfsServer: 192.168.1.199
  persistentVolumes:
    - name: apulis-mysql-v1
      capacity: 2000Mi
      path: /data/nfs-share-dir/apulisedge/v1
    - name: apulis-mysql-v2
      capacity: 1000Mi
      path: /data/nfs-share-dir/apulisedge/v1




