apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeedge-cloud
  namespace: {{ .Values.apulis.namespace}}
  labels:
    system: apulisedge
spec:
  {{- with .Values.apulis.cloud }}
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: kubeedge-cloud
  template:
    metadata:
      labels:
        app: kubeedge-cloud
    spec:
      nodeSelector:
        apulisedge-cloud: active
        archType: amd64
      hostAliases:
      - ip: {{ .env.harborIp }}
        hostnames:
        - {{ .env.harborHostName }}
        - {{ .env.cloudHostName }}
      containers:
      - name: {{ .kubeedgeImage.name }}
        image: "{{ .kubeedgeImage.repository }}:{{ .kubeedgeImage.tag }}"
        imagePullPolicy: {{ .kubeedgeImage.pullPolicy }}
        ports:
        - name: hubHttps
          containerPort: {{ .kubeedgeConfig.cloudHubHttpsPort }}
          protocol: TCP
        - name: hubQuic
          containerPort: {{ .kubeedgeConfig.cloudHubQuicPort}}
          protocol: UDP
        - name: hubWebsocket
          containerPort: {{ .kubeedgeConfig.cloudHubWebsocketPort}}
          protocol: TCP
        volumeMounts:
        - mountPath: /root/.kube/config
          name: kubeconf
        - mountPath: /etc/kubeedge/config/cloudcore.yaml
          name: appconfig
          subPath: cloudcore.yaml
      volumes:
      - name: kubeconf
        hostPath:
          path: /etc/kubernetes/admin.conf
      - name: appconfig
        configMap:
          name: kubeedge-cloud-cm
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
  {{- end }}