apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeedge-cloud-cm
  namespace: {{ .Values.kubeedge.namespace }}
data:
  cloudcore.yaml: |+
    apiVersion: cloudcore.config.kubeedge.io/v1alpha1
    kind: CloudCore
    kubeAPIConfig:
      burst: 200
      contentType: application/vnd.kubernetes.protobuf
      kubeConfig: /root/.kube/config
      master: ""
      qps: 100
    leaderelection:
      LeaderElect: false
      LeaseDuration: 15s
      RenewDeadline: 10s
      ResourceLock: endpointsleases
      ResourceName: cloudcorelease
      ResourceNamespace: kubeedgels
      RetryPeriod: 2s
    modules:
      cloudHub:
      {{- if (eq .Values.kubeedge.type "single") }}
        advertiseAddress:
        - {{ .Values.kubeedge.singleMode.advertiseAddress }}
      {{- end }}
        edgeCertSigningDuration: 365
        enable: true
        https:
          address: 0.0.0.0
          enable: true
          port: 10002
        keepaliveInterval: 30
        nodeLimit: 1000
        tlsCAFile: /etc/kubeedge/ca/rootCA.crt
        tlsCAKeyFile: /etc/kubeedge/ca/rootCA.key
        tlsCertFile: /etc/kubeedge/certs/server.crt
        tlsPrivateKeyFile: /etc/kubeedge/certs/server.key
        unixsocket:
          address: unix:///var/lib/kubeedge/kubeedge.sock
          enable: true
        websocket:
          address: 0.0.0.0
          enable: true
          port: 10000
        writeTimeout: 30
      deviceController:
        buffer:
          deviceEvent: 1
          deviceModelEvent: 1
          updateDeviceStatus: 1024
        context:
          receiveModule: devicecontroller
          responseModule: cloudhub
          sendModule: cloudhub
        enable: true
        load:
          updateDeviceStatusWorkers: 1
      edgeController:
        buffer:
          configMapEvent: 1
          deletePod: 1024
          endpointsEvent: 1
          podEvent: 1
          queryConfigMap: 1024
          queryEndpoints: 1024
          queryNode: 1024
          queryPersistentVolume: 1024
          queryPersistentVolumeClaim: 1024
          querySecret: 1024
          queryService: 1024
          queryVolumeAttachment: 1024
          secretEvent: 1
          serviceEvent: 1
          updateNode: 1024
          updateNodeStatus: 1024
          updatePodStatus: 1024
        context:
          receiveModule: edgecontroller
          responseModule: cloudhub
          sendModule: cloudhub
        enable: true
        load:
          deletePodWorkers: 4
          queryConfigMapWorkers: 4
          queryEndpointsWorkers: 4
          queryNodeWorkers: 4
          queryPersistentVolumeClaimWorkers: 4
          queryPersistentVolumeWorkers: 4
          querySecretWorkers: 4
          queryServiceWorkers: 4
          queryVolumeAttachmentWorkers: 4
          updateNodeStatusWorkers: 1
          updateNodeWorkers: 4
          updatePodStatusWorkers: 1
        nodeUpdateFrequency: 10
      syncController:
        enable: true