// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/createNode": {
            "post": {
                "description": "create edge node",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "node"
                ],
                "summary": "create edge node",
                "parameters": [
                    {
                        "description": "userId:user id, userName: user name",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/node.CreateEdgeNodeReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpserver.APISuccessResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/node.CreateEdgeNodeRsp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpserver.APIErrorResp"
                        }
                    }
                }
            }
        },
        "/listNode": {
            "post": {
                "description": "list edge nodes",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "node"
                ],
                "summary": "list edge nodes",
                "parameters": [
                    {
                        "description": "userId:user id, userName: user name",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/node.ListEdgeNodesReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code:0, msg:OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpserver.APISuccessResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/node.ListEdgeNodesRsp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "code:30000, msg:db error",
                        "schema": {
                            "$ref": "#/definitions/httpserver.APIErrorResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "httpserver.APIErrorResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "httpserver.APISuccessResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "object"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "node.CreateEdgeNodeReq": {
            "type": "object",
            "properties": {
                "nodeName": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                },
                "userName": {
                    "type": "string"
                }
            }
        },
        "node.CreateEdgeNodeRsp": {
            "type": "object",
            "properties": {
                "node": {
                    "$ref": "#/definitions/nodeentity.NodeBasicInfo"
                }
            }
        },
        "node.ListEdgeNodesReq": {
            "type": "object",
            "properties": {
                "pageNum": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "userId": {
                    "type": "integer"
                },
                "userName": {
                    "type": "string"
                }
            }
        },
        "node.ListEdgeNodesRsp": {
            "type": "object",
            "properties": {
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/nodeentity.NodeBasicInfo"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "nodeentity.NodeBasicInfo": {
            "type": "object",
            "required": [
                "id",
                "name",
                "osImage",
                "roles",
                "runtime",
                "status",
                "userId",
                "userName"
            ],
            "properties": {
                "createAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "interIp": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "osImage": {
                    "type": "string"
                },
                "outerIp": {
                    "type": "string"
                },
                "providerId": {
                    "type": "string"
                },
                "roles": {
                    "type": "string"
                },
                "runtime": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updateAt": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                },
                "userName": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "alpha",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "ApulisEdge Cloud API",
	Description: "ApulisEdge cloud server.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
